ALTER TABLE PUBLIC.PARTICIPANT ADD ADDITIONAL_IDS CHARACTER VARYING(1024);
ALTER TABLE PUBLIC.PARTICIPANT ADD FIRST_REGISTRATION DATE;
ALTER TABLE PUBLIC.PARTICIPANT ADD MIGRATION_CODE CHARACTER VARYING(255);
